apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservico-o-v1
  labels:
    app: microservico-o
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservico-o
      version: v1
  template:
    metadata:
      labels:
       app: microservico-o
       version: v1
    spec:
      containers:
        - name: microservico-o-container
          image: anhaya/microservico-o:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080